# Generated by Django 3.1.7 on 2021-03-31 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(default='Book Description')),
                ('thumbnail', models.ImageField(default='default.jpg', upload_to='book_thumbnail')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authors.authorprofile')),
            ],
        ),
    ]
